name: Release

on:
  push:
    tags:
      - 'v*' # v0.8.1

jobs:

  publish:
    name: Installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Dependencies
        run: |
          sudo apt-get install -y jq

      - name: Release Tag
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Release SHA
        run: |
          echo "release tag: ${RELEASE_TAG}"
          ASSET_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/mchmarny/followme/releases/tags/${RELEASE_TAG}" | jq '.assets[] | select(.name=="followme-darwin-amd64.tar.gz") | .url')
          ASSET_SHA=$(curl -L -f -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ASSET_URL 2> /dev/null | shasum -a 256 | cut -f1 -d" ")
          echo "release sha: '${ASSET_SHA}'"
          echo "ASSET_SHA=${ASSET_SHA}" >> $GITHUB_ENV
          
      - name: Formula
        run: |
          echo "release tag: '${RELEASE_TAG}'"
          echo "release sha: '${ASSET_SHA}'"
          sed -e "s/TAGVALUE/${RELEASE_TAG}/g" -e "s/SHAVALUE/${ASSET_SHA}/g" Template/followme.tmpl > Formula/followme.rb

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "formula ${RELEASE_TAG}"
          git push