name: Release

on:
  push:
    tags:
      - 'v*' # v0.8.1

jobs:

  publish:
    name: Installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Dependencies
        run: |
          sudo apt-get install -y jq

      - name: Release Tag
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Release SHA
        run: |
          echo "release tag: ${RELEASE_TAG}"
          wget "https://github.com/mchmarny/followme/releases/download/${RELEASE_TAG}/followme-darwin-amd64.tar.gz"
          MAC_SHA=$(shasum -a 256 followme-darwin-amd64.tar.gz | cut -f1 -d" ")
          echo "mac release sha: '${MAC_SHA}'"
          echo "MAC_SHA=${MAC_SHA}" >> $GITHUB_ENV
          wget "https://github.com/mchmarny/followme/releases/download/${RELEASE_TAG}/followme-linux-amd64.tar.gz"
          LINUX_SHA=$(shasum -a 256 followme-linux-amd64.tar.gz | cut -f1 -d" ")
          echo "linux release sha: '${LINUX_SHA}'"
          echo "LINUX_SHA=${LINUX_SHA}" >> $GITHUB_ENV
          
      - name: Formula
        run: |
          mkdir -p Formula
          echo "release tag: '${RELEASE_TAG}'"
          echo "release sha (mac): '${MAC_SHA}'"
          echo "release sha (linux): '${LINUX_SHA}'"
          sed -e "s/TAGVALUE/${RELEASE_TAG}/g" -e "s/MAC_SHA/${MAC_SHA}/g" -e "s/LINUX_SHA/${LINUX_SHA}/g" Template/followme.tmpl > Formula/followme.rb

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "formula ${RELEASE_TAG}"
          git push